'use client';

import { Download } from 'lucide-react';
import { AnalysisResult } from '@/types';

interface ExportButtonProps {
  analysis: AnalysisResult;
}

export default function ExportButton({ analysis }: ExportButtonProps) {
  const exportToPDF = () => {
    const content = `
RESUME ANALYSIS REPORT
Generated on: ${new Date(analysis.createdAt).toLocaleDateString()}

MATCH SCORE: ${analysis.analysis.matchScore}%

SUMMARY:
${analysis.analysis.summary}

MATCHING SKILLS:
${analysis.analysis.skillsMatch.map(skill => `• ${skill}`).join('\n')}

SKILLS TO DEVELOP:
${analysis.analysis.skillsGap.map(skill => `• ${skill}`).join('\n')}

RECOMMENDATIONS:
${analysis.analysis.recommendations.map(rec => `• ${rec}`).join('\n')}

AI ANALYSIS:
${analysis.aiReport || 'AI analysis not available'}

---
Generated by ResuScan - AI-Powered Resume Analysis Platform
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `resume-analysis-${analysis.analysis.matchScore}%-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={exportToPDF}
      className="flex items-center px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
    >
      <Download className="h-4 w-4 mr-2" />
      Export Report
    </button>
  );
}